# The development environment runs the live application on the development server.
services:
  api:
    image: ${APPLICATION_API_IMAGE}
    environment:
      - NODE_ENV=production

  jobs:
    image: ${APPLICATION_JOBS_IMAGE}

  # add logging in production environment
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: rcb-rag-api-otel-collector
    environment:
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      HONEYCOMB_DATASET: ${HONEYCOMB_DATASET}
    volumes:
      - ../otel-config.yaml:/etc/otel/config.yaml:ro
    command: ["--config", "/etc/otel/config.yaml"]
    networks:
      - core-network
