version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      - chromadb
    env_file:
      - ../config/env/.env.development

  chromadb:
    image: chromadb/chroma
    volumes:
      - chroma-data:/chroma/chroma
    env_file:
      - ../config/env/.env.development

  mongodb:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    env_file:
      - ../config/env/.env.development

volumes:
  chroma-data:
  mongo-data:
