# The development environment runs the live application on the development server.
services:
  api:
    image: ${APPLICATION_API_IMAGE}
    environment:
      - NODE_ENV=development

  jobs:
    image: ${APPLICATION_JOBS_IMAGE}
