version: '3.8'

services:
  llm-proxy:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      - chromadb
    env_file:
      - ../config/env/.env.development

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/chroma

volumes:
  chroma-data:
