name: Lint & Build
run-name: Lint & Build

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: true
        type: string
      target_env:
        description: 'The deployment environment e.g. production or development'
        required: true
        type: string
      skip_deploy:
        description: 'Skip the deploy step (true/false)'
        required: true
        type: boolean

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  trigger-deploy:
    needs: lint
    name: Publish & Deploy
    if: ${{ inputs.skip_deploy == false }}
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}
